[package]
name = "tsv"
description = "TSV utilities"
version = "0.0.2"
authors = ["Oliver Ruebenacker <oliverr@broadinstitute.org>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/broadinstitute/tsv"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs-err = "2.8.1"
clap = { version = "3.2.22", features = ["cargo"] }
jati = { git = "https://github.com/broadinstitute/jati", rev = "68de8a2f" }
